// Generated by CoffeeScript 1.10.0
var setProto;

setProto = require("setProto");

module.exports = function(value, type) {
  if (type && type.prototype) {
    setProto(value, type.prototype);
  } else if (type === null) {
    setProto(value, null);
  }
  return value;
};
